### ISSUE TITLE
Enhancement: Gaia queries for stellar properties

### ISSUE THREAD

**Issue by bmorris3** [tcjansen/GSoC#2]
Enhancement proposal: use astroquery to get the stellar distance and radius like I do in [this example](https://gist.github.com/bmorris3/685db348daf6dac409e2ee1726f0a60b), rather than hard-coding the answers into the notebook. You'll need to come up with a more clever way of selecting the correct answer from the query response than choosing the first row, as I did in the example. You might find that the answer is the star closest to the input coordinates. You can measure distances between coordinates using [`SkyCoord.separation()`](http://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord.separation). 📐

**Comment by tcjansen** [comment]
Just as an update on this, the `astroquery.Gaia` table has a column for distance to the input coordinate, so I used that in place of `SkyCoord.separation()`. 

As for choosing the star nearest to the given coordinates (which is what I would have suggested as well), it worked great for HAT-P-11, but became a problem when SkyCoord and Gaia disagreed on the RA and Dec of Trappist-1... they give:
```
SkyCoord: 346.622, -5.0414
Gaia: 346.626, -5.0435
```
Since Gaia has a source closer to the SkyCoord coordinates than its TRAPPIST-1 coordinates, it selects the wrong object. 

What's more, Gaia unfortunately doesn't have a stellar radius for TRAPPIST-1...
All to say I think we need to query a different catalog for this star!

**Comment by bmorris3** [comment]
Ok, let's supply it with the radius, distance, and effective temperature parameters for TRAPPIST-1 manually from [Gillon et al. 2017](http://adsabs.harvard.edu/abs/2017Natur.542..456G).
